server {
    listen 80;
    server_name _;

    location /api/ {
        proxy_pass http://host.docker.internal:8080/;
    }

    location /admin-api/ {
        proxy_pass http://host.docker.internal:8081/;
    }
}
