USE ai_listen;

CREATE TABLE IF NOT EXISTS `users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mobile` VARCHAR(20) NOT NULL,
  `wechat_open_id` VARCHAR(64) DEFAULT '',
  `union_id` VARCHAR(64) DEFAULT '',
  `nickname` VARCHAR(64) DEFAULT '',
  `avatar` VARCHAR(255) DEFAULT '',
  `gender` TINYINT NOT NULL DEFAULT 0 COMMENT '0未知1男2女',
  `birthday` DATE DEFAULT NULL,
  `city_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `bio` VARCHAR(255) DEFAULT '',
  `vip_level` TINYINT NOT NULL DEFAULT 0,
  `user_status` TINYINT NOT NULL DEFAULT 1 COMMENT '1正常0禁用',
  `last_login_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_mobile` (`mobile`),
  KEY `idx_wechat_open_id` (`wechat_open_id`),
  KEY `idx_city_id` (`city_id`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `provider_applications` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `real_name` VARCHAR(64) NOT NULL,
  `id_card_no` VARCHAR(128) NOT NULL,
  `id_card_front` VARCHAR(255) NOT NULL,
  `id_card_back` VARCHAR(255) NOT NULL,
  `face_verify_status` TINYINT NOT NULL DEFAULT 0,
  `agreement_signed` TINYINT NOT NULL DEFAULT 0,
  `city_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `intro` VARCHAR(500) DEFAULT '',
  `photos` JSON DEFAULT NULL,
  `service_desc` VARCHAR(500) DEFAULT '',
  `audit_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0待审1通过2驳回',
  `reject_reason` VARCHAR(255) DEFAULT '',
  `submitted_at` DATETIME DEFAULT NULL,
  `audited_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_city_id` (`city_id`),
  KEY `idx_audit_status` (`audit_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `providers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `provider_no` VARCHAR(32) NOT NULL,
  `zodiac` VARCHAR(16) DEFAULT '',
  `constellation` VARCHAR(16) DEFAULT '',
  `level` VARCHAR(16) DEFAULT '',
  `score` DECIMAL(4,2) NOT NULL DEFAULT 0.00,
  `total_orders` INT NOT NULL DEFAULT 0,
  `total_income` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `service_status` TINYINT NOT NULL DEFAULT 3 COMMENT '1空闲2工作中3休息',
  `online_status` TINYINT NOT NULL DEFAULT 0,
  `city_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `intro` VARCHAR(500) DEFAULT '',
  `tags` JSON DEFAULT NULL,
  `commission_rate` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `complaint_count` INT NOT NULL DEFAULT 0,
  `cancel_count` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_id` (`user_id`),
  UNIQUE KEY `uk_provider_no` (`provider_no`),
  KEY `idx_city_id` (`city_id`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
